import matplotlib.pyplot as plt
import numpy as np

# Data
labels = [
    'Doctor <--> Wait Time',
    'Doctor <--> Facility',
    'Doctor <--> Staff',
    'Staff <--> Wait Time',
    'Facility <--> Wait Time',
    'Billing <--> Doctor',
    'Facility <--> Staff',
    'Billing <--> Wait Time',
    'Communication <--> Doctor',
    'Billing <--> Staff',
    'Communication <--> Wait Time',
    'Billing <--> Facility',
    'Communication <--> Staff',
    'Communication <--> Facility',
    'Billing <--> Communication'
]

values = [
    285,
    215,
    205,
    160,
    145,
    120,
    105,
    95,
    95,
    85,
    80,
    70,
    40,
    30,
    25
]

# --- Create the Radar Chart ---

num_vars = len(labels)

# Compute angle for each axis.
angles = np.linspace(0, 2 * np.pi, num_vars, endpoint=False).tolist()

# The radar chart needs to be closed, so add the first value and angle to the end.
values = values + values[:1]
angles = angles + angles[:1]

# Set up the plot.
fig, ax = plt.subplots(figsize=(12, 12), subplot_kw=dict(polar=True))

# Plot the data.
ax.plot(angles, values, color='darkblue', linewidth=2, linestyle='solid', label='Number of Occurrences')
ax.fill(angles, values, color='lightcoral', alpha=0.3)

# Set the radial grid lines.
ax.set_yticks(np.linspace(0, max(values) * 1.0, 5))
ax.set_yticklabels([f'{int(val):,}' for val in np.linspace(0, max(values) * 1.0, 5)], color='gray', fontsize=8)


# Set the title.
ax.set_title('Top 20 \'Conflict Archetypes\' in High-Rated Negative Reviews', va='bottom', fontsize=16)

# Set the y-axis limits and tick labels.
max_value = max(values)
# Increase ylim to create more space between the plot and the labels.
ax.set_ylim(0, max_value * 1.3) # Increased buffer for labels

# Custom labels placement to avoid overlap
# Hide default xticklabels generated by set_xticks if you plan to replace them
ax.set_xticks(angles[:-1]) # This sets the positions of the radial grid lines for the labels
ax.set_xticklabels([]) # Hide the default tick labels

# Loop through each label and place it manually
for i, (label, angle) in enumerate(zip(labels, angles[:-1])):
    # Determine rotation. Often, labels on the left side are better read horizontally,
    # and labels on the right side might benefit from some rotation.
    # A simple approach is to rotate labels that are on the left side of the chart.
    if np.degrees(angle) > 90 and np.degrees(angle) < 270:
        rotation_angle = np.degrees(angle) + 90 # Rotate labels on the left side
    else:
        rotation_angle = np.degrees(angle) - 90 # Rotate labels on the right side

    # Adjust text position (r - radius, theta - angle)
    # The 'r' value here is the radial distance from the center.
    # ax.get_ylim()[1] is the maximum radius of the plot.
    # We add a buffer to place the text outside the plot.
    ax.text(angle, ax.get_ylim()[1] * 1.05, label,
            rotation=rotation_angle,
            horizontalalignment='center',
            verticalalignment='center',
            fontsize=10,
            color='black')


# Customize grid appearance
ax.grid(True, linestyle='--', alpha=0.7)

# Add a legend.
ax.legend(loc='upper right', bbox_to_anchor=(1.3, 1.1))

plt.show()